version: '3'

services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    expose:
      - 6379

  teleport_app:
    image: teleport_app
#    build: .
    volumes:
      - ./app:/app
      - /tmp/uploads:/uploads
    working_dir: /app
    
#    user: "1000:133"
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        teleport_app:app
    ports:
      - "5000:5000"

  celery_app:
    image: teleport_app
#    build: .
    environment: 
      - REDIS_HOST=redis
    volumes:
      - ./app:/app
      #- ./app/uploads:/app/uploads
      - /tmp/uploads:/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app

#    user: "1000:133"
    command: celery -A teleport_worker worker

    
